name: Generate Hacker Red Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate hacker red snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Amal06429

          # ðŸ”´ HACKER RED THEME
          color_snake: "#ff0033"
          color_dots: "#0d1117,#330000,#660000,#990000,#ff0033"

          outputs: |
            dist/hacker-red-snake.svg
            dist/hacker-red-snake-dark.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
